#pragma once
#include <string>

enum class Command {
    INSERTAVL, DELETEAVL, SEARCHAVL, PRINTAVL,
    SPUSH, SPOP, SPRINT,
    APUSH, AINSERT, APRINT, ADELETE,
    QPUSH, QPOP, QPRINT,
    ADDHEADSL, ADDTAILSL, ADDAFTERSL, ADDBEFORESL,
    REMOVEHEADSL, REMOVETAILSL, REMOVEAFTERSL, REMOVEBEFORESL,
    DELETEBYVALUESL, SEARCHBYVALUESL, PRINTSL,
    ADDHEADDL, ADDTAILDL, ADDAFTERDL, ADDBEFOREDL,
    PRINTDL, BPRINTDL, SEARCHBYVALUEDL, DELETEBYVALUEDL,
    UNKNOWN
};
