#pragma once
#include <string>

enum class Command {
    INSERTAVL, DELETEAVL, SEARCHAVL, PRINTAVL,
    SPUSH, SPOP, SPRINT, SSIZE,
    APUSH, AINSERT, APRINT, ADELETE, AGET, ASWAP, ASIZE,
    QPUSH, QPOP, QPRINT,
    ADDHEADSL, ADDTAILSL, ADDAFTERSL, ADDBEFORESL,
    REMOVEHEADSL, REMOVETAILSL, REMOVEAFTERSL, REMOVEBEFORESL,
    DELETEBYVALUESL, SEARCHBYVALUESL, PRINTSL,
    ADDHEADDL, ADDTAILDL, ADDAFTERDL, ADDBEFOREDL, REMOVEHEADDL,
    REMOVETAILDL, REMOVEAFTERDL, REMOVEBEFOREDL,
    PRINTDL, BPRINTDL, SEARCHBYVALUEDL, DELETEBYVALUEDL,
    UNKNOWN
};
